consumer_key: ''
consumer_secret: ''
access_token: ''
access_token_secret: ''
bearer_token: ""
client_id: ''
client_secret: ''
url: 'https://twitter.com/login'
login: 'Coloque seu login'
password: 'Coloque sua senha'
blacklist:
 - 'Página Inicial'
 - 'Explorar'
 - 'Tendências de Brasil'
 - 'Para você'
 - 'Assuntos do Momento'
 - 'Notícias'
 - 'Esportes'
 - 'Entretenimento'
 - 'Pop'
 - '·'
 - 'Para ver as teclas de atalho, pressione o ponto de interrogação'
 - 'Acessibilidade' 
 - 'Mensagens' 
 - 'Perfil' 
 - 'Mais' 
 - 'IA search' 
 - 'Termos de Serviço' 
 - 'Política de Privacidade' 
 - '© 2023 X Corp.' 
 - 'Twitter Blue' 
 - 'Notificações' 
 - 'Tweetar' 
 - 'Informações de anúncios' 
 - 'Listas' 
 - 'Itens salvos' 
 - '@IAsearch333' 
 - '20+' 
 - 'Política de cookies' 
